# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image: 
  file: .gitpod.Dockerfile
tasks:
  - init: 'composer create-project laravel/laravel ircite-mcc-v1'
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8000
    visibility: public

vscode:
  extensions:
    - felixfbecker.php-debug
